version: "3.8"
services:
  backend:
    build: ./backend
    container_name: text-to-gif-back
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    container_name: text-to-gif-front
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true